name: Triggered on push 3
on:
  push:
    branches:
      - master

jobs:
  build:
    name: Third 
    runs-on: [self-hosted, Linux, X64]
    steps:
      - name: Name301
        uses: actions/checkout@v2
      - name: Name302
        run: pwd; ls -lR; sleep 120; echo "End13"

